### PR TITLE
Removed support for MRI ruby versions lower than 2.2

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
Rationale: https://discuss.lotusrb.org/t/supported-ruby-vms/28

### CODE REVIEW

**Comment by jodosha** [comment]
@AlfonsoUceda :+1:

**Comment by jdickey** [comment]
Guys, I realise I'm [late to the discussion](https://discuss.lotusrb.org/t/supported-ruby-vms/28/12?u=jdickey), but...

image

**Comment by joneslee85** [comment]
:+1:  kill it

**Comment by AlfonsoUceda** [comment]
I'm going to close this PR

**Pull request closed without merging**
