### PR TITLE
Create default gitignore template and template for file db

### LINKED ISSUE #454: New command: when --database is sepecified, it generates empty .gitignore
Steps to reproduce:

```shell
➜ lotus new bookshelf --database=postgres
➜ cat bookshelf/.gitignore # EMPTY
```

Expected:

```shell
➜ cat bookshelf/.gitignore
/public/assets*
/tmp
```

### PR DESCRIPTION
**Pull request by davydovanton**
Fixed #454

### CODE REVIEW

**Comment by jodosha** [comment]
@davydovanton You're a machine! :100:

**Comment by davydovanton** [comment]
:D
@jodosha do you think about replacing several parts of templates? This will help remove DRY in partials.

**Comment by jodosha** [comment]
@davydovanton Let's keep it simple for now. Thanks for the suggestion BTW :smile:

**Comment by davydovanton** [comment]
okay :)
thanks for merge!

**Pull request merged**
