### PR TITLE
Converts camel case app name into snake case when looking for applica…

### PR DESCRIPTION
**Pull request by jasoncharnes**
…tion during action generation. Also found an issue with those of use who experience an issue when generating actions with zsh and have to use '/' instead of '#' between controller and action.

#381

### CODE REVIEW

**Comment by joneslee85** [comment]
is it possible to have test ?

**Comment by jasoncharnes** [comment]
Absolutely, don't know where my head was at last night. Just pushed the tests.

**Comment by joneslee85** [comment]
:+1:

**Comment by jodosha** [comment]
@jasoncharnes Thank you for this fix :blue_heart:

**Comment by jasoncharnes** [comment]
@jodosha glad to do it! I appreciate the opportunity to contribute.

**Pull request merged**
