### PR TITLE
Generate lib/app_name/mailers/templates on app creation

### PR DESCRIPTION
**Pull request by joneslee85**

### CODE REVIEW

**Comment by jodosha** [comment]
@joneslee85 Great quick response! :clap: 

Why do we need these new `.gitkeep` files? `lib/lotus/generators/application/container/lib/chirp/mailers/.gitkeep`

I mean, `chirp` is part of a fixture, right?

**Comment by joneslee85** [comment]
@jodosha yup

**Comment by jodosha** [comment]
@joneslee85 I mean, should we remove them?

**Comment by joneslee85** [comment]
@jodosha we should, another PR

**Pull request merged**
