### PR TITLE
JRuby testing

### PR DESCRIPTION
**Pull request by PragTob**
This lets tests run on travis. I use jruby-head while JRuby works forward to the 9k release - it only updates when builds are green :)

I also fixed the install by including a jruby-specific gem for JRuby.

Cheers,
Tobi

### CODE REVIEW

**Comment by PragTob** [comment]
Oh yeah this #146

**Comment by PragTob** [comment]
mistake on my part, investigating (new shell tab, other ruby)

**Comment by PragTob** [comment]
rebased and squashed into two imo meaningful commits. It installs on JRuby and the tests start running, unfortunately the specs still fail, but that can be left for another time.

**Comment by jodosha** [comment]
@PragTob Thanks for starting with this. :+1:  I'm going to merge, so it can serve as base for you or somebody else who want to tackle this task.

I had the impression that MiniTest run the specs in parallel on JRuby. Is it correct?

**Comment by PragTob** [comment]
I don't use minitest in my projects, so Ino idea sorry.

Thanks for the merge! :)

**Comment by jodosha** [comment]
@PragTob I was talking about the test suite of this project. ;)

**Pull request merged**
