### PR TITLE
Adds support to initializers.

### PR DESCRIPTION
**Pull request by lucasallan**
Closes https://github.com/lotus/lotus/issues/367

### CODE REVIEW

**Comment by jodosha** [comment]
@lucasallan Thanks for this PR. I guess you forgot to commit some file, because the build is failing and you are referencing `CollaborationInitializer1` from tests.

**Comment by manuwell** [comment]
:+1:

**Comment by lucasallan** [comment]
@jodosha I'll fix it later today. Thanks

**Comment by lucasallan** [comment]
@jodosha Done.

**Comment by joneslee85** [comment]
looks good, have you tried to run the generator yet? just want to make sure

**Comment by jodosha** [comment]
> Done.

@lucasallan Not really :wink: 

New generated applications (both container and application architectures) should have this new directory. Can you expand this PR? Thank you :smile:

**Comment by lucasallan** [comment]
@jodosha Sure. I'll work on it again later today.

**Comment by joneslee85** [comment]
@lucasallan ping :)

**Comment by lucasallan** [comment]
@joneslee85 Sorry, I'll finish it soon. I got a cold last week and I wasn't able to work.

**Comment by lucasallan** [comment]
I generated both container and app and they both have the `config/initializers/` directory.

**Comment by jodosha** [comment]
@lucasallan Hey, thanks for the progress. :+1: There are still tests to write for `config/initializers`. As a reference see: https://github.com/lotus/lotus/search?utf8=%E2%9C%93&q=gitkeep

Thank you! :+1:

**Comment by lucasallan** [comment]
@jodosha I just added the missing tests. Thanks!

**Comment by joneslee85** [comment]
:+1:

**Comment by jodosha** [comment]
@lucasallan Thank you very much, merging this. :+1:

**Pull request merged**
