### PR TITLE
Refactoring ApplicationName class

### PR DESCRIPTION
**Pull request by joneslee85**
* Minor cleanup
* Minor doc refactoring
* Add test for .invalid?

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
:+1:

**Comment by jodosha** [comment]
@joneslee85 Why this has a `v0.7.0` milestone and it was already merged in master?

**Comment by joneslee85** [comment]
@jodosha oh darn, I did not check before merging, we did not have branch off the 0.6.x yet. Since this is a very trivial change, are you okay if I set this for 0.6 instead?

**Comment by jodosha** [comment]
@joneslee85 Does it changes the behavior of `lotus new`? It seems only a refactoring. If so, please add the 0.6 milestone and let's move on.

**Comment by joneslee85** [comment]
@jodosha just a refactoring, I'll tag it 0.6

**Comment by jodosha** [comment]
@joneslee85 Cool :+1:

**Pull request merged**
