### PR TITLE
Fix not completed PR with new rspec data in spec_helper

### PR DESCRIPTION
**Pull request by davydovanton**
Fixed #434. Add new data to fixtures partials and add new data to
container architecture template. :sweat:

### CODE REVIEW

**Comment by joneslee85** [comment]
+1 on green

**Comment by davydovanton** [comment]
@joneslee85 all base tests is green :tada: 
https://travis-ci.org/lotus/lotus/builds/99671950

**Comment by davydovanton** [comment]
thanks for merge @joneslee85! :+1:

**Pull request merged**
