### PR TITLE
Update test file for Lotusrc class

### PR DESCRIPTION
**Pull request by davydovanton**
* Use existing `@lotusrc` instead `Lotus::Lotusrc.new(@root)`;
* Add missing test for checking returned options keys;

### CODE REVIEW

**Comment by joneslee85** [comment]
@davydovanton can you please update the description what the refactoring is?

**Comment by davydovanton** [comment]
@joneslee85 yes, of course

**Comment by AlfonsoUceda** [comment]
@davydovanton because you are refactoring this test, can you extract to a before block below https://github.com/lotus/lotus/pull/446/files#diff-b83ba0c0465de991a609fb85be6dd33dR4 the common things except the `Dir.chdir 'path'` line? to avoid duplicated code. what do you think?

**Comment by davydovanton** [comment]
@AlfonsoUceda done. I replaced all `before` block but for each case I created different path to lotusrc file. What do you think? This is better for you?

**Comment by AlfonsoUceda** [comment]
@davydovanton could you do the same for after block? then :+1: to me, thank you so much ;)

**Comment by davydovanton** [comment]
oh, sorry I did not notice `after` block :disappointed: 
Done too

**Comment by davydovanton** [comment]
@AlfonsoUceda could you stop current travis build? (https://travis-ci.org/lotus/lotus/builds/100646008) this will save our time :smiley:

**Comment by AlfonsoUceda** [comment]
haha don't worry ;) stopped

**Comment by davydovanton** [comment]
nice, thank you very much @AlfonsoUceda! :tada:

**Comment by AlfonsoUceda** [comment]
@davydovanton merging, because this is only a refactor in a test. thanks!!
cc @lotus/core-team

**Comment by davydovanton** [comment]
Thanks for merge!

**Pull request merged**
