### PR TITLE
Add DBConsole command

### PR DESCRIPTION
**Pull request by Linuus**
As discussed here: https://github.com/lotus/lotus/issues/123

I still haven't gotten around to add the tests yet, but I thought I'd open the PR anyway.

Have I missed any options?

Related: https://github.com/lotus/model/pull/150

### CODE REVIEW

**Comment by joneslee85** [comment]
I am good with this PR :+1:

**Comment by jodosha** [comment]
@Linuus @joneslee85 I'm confused. This proposed feature should be used by passing manually CLI args for authentication, database etc..?

**Comment by joneslee85** [comment]
@jodosha you are right, I totally forget about that.

@Linuus the idea is not to provide username/password explicitly. The idea that the CLI would pick up the configuration and handle everything for you.

For example:

`bundle exec lotus dbconsole`
`LOTUS_ENV=test bundle exec lotus dbconsole`

**Comment by Linuus** [comment]
Hmm well, of course! :)




I'll fix it when I'm back home after the weekend.

**Comment by jodosha** [comment]
@Linuus Thank you very much! :+1:

**Comment by Linuus** [comment]
@jodosha, @joneslee85 Do we still want to keep the CLI options so you may pass in overrides? Perhaps that's not necessary.

**Comment by joneslee85** [comment]
@Linuus my vote is to remove them, it should be the job of our configuration file

**Comment by jodosha** [comment]
@Linuus I agree with @joneslee85

**Comment by Linuus** [comment]
@joneslee85 @jodosha I have another question.

Right now this only works with the database configuration set in `lib/my_app.rb`, since I use `Lotus::Model.configuration`. You can pass in a name, like `lotus dbconsole web` but I don't do anything with that parameter at the moment.

How do I get the configuration for the `Web` app in this case?

I think I can do
```ruby
Web::Application.load!
Web::Application.configuration.adapter   #=> {:type=>:sql, :uri=>"postgres://localhost/foo_development"}
```

Is that the way to do it?

Can I get an adapter object somehow? Like when I run `Lotus::Model.configuration.adapter_config`?

**Comment by joneslee85** [comment]
@Linuus very good question, you could access the `adapter_config` (after running `.load!`) by:

```ruby
Web::Model.configuration.adapter_config
```

FYI, the `Lotus::Loader#_configure_model_framework!` duplicate the Model and set it under your app namespace.

It is ideal not to run `.load!` to avoid loading overhead. When you are online tonight, please ping me, I'll see what I could do to help you no this.

**Comment by joneslee85** [comment]
It'd be great if you could test for sqlite uri string escaping

**Comment by joneslee85** [comment]
@Linuus looks good, I am not so sure how are we going to do integration test for this feature, but for now can you please do hand test? Once good, we could merge

**Comment by Linuus** [comment]
Sure. I was unsure myself on how to do it. I tried the other day but nothing good came out of it ;)

I have tested it with sqlite and postgresql (will test mysql too). Only with the default container architecture though.

Should I test something else?

**Comment by joneslee85** [comment]
@Linuus should be good for now.

**Comment by joneslee85** [comment]
ping @Linuus - any update?

**Comment by Linuus** [comment]
Sorry for being slow. I will test mysql tonight.

**Comment by Linuus** [comment]
@joneslee85 I tested with mysql and it seems to work good! :+1:

**Comment by joneslee85** [comment]
Woo! Much thanks

**Pull request merged**
