### PR TITLE
[f] Application generator

### LINKED ISSUE #157: Application generator
**Taker**: @hieuk09 

## What

Introduce a new command `lotus generate`.

## Why

Lotus generator (`lotus new`) generates only one application `apps/web`. If developers want to add other apps, this will be the official way to do that.

### CLI

```shell
% lotus generate app admin
```

  * `app` is the subject of what we want to generate
  * `admin` is the name of the application under `apps/`
  * Optional `--application-base-url`. Defaults to the app name.
  * Optional `--test`. Defaults to the contents of `.lotusrc` or to `minitest`, if that file is missing.

### Output

  * It will generate a Lotus application with the given name: `apps/admin`.
  * Amend `config/environment.rb`

### Files

```ruby
# config/environment.rb
require 'rubygems'
require 'bundler/setup'
require 'lotus/setup'
require_relative '../lib/bookshelf'
require_relative '../apps/web/application'
require_relative '../apps/admin/application' # NEW LINE

Lotus::Container.configure do
  #
  # !!! ATTENTION !!! New applications should be put at the top of this block
  #
  mount Admin::Application, at: '/admin' # NEW LINE
  mount Web::Application, at: '/'
end
```

### PR DESCRIPTION
**Pull request by hieuk09**
Fixes #157

### CODE REVIEW

**Comment by joneslee85** [comment]
@hieuk09 do you need any help with writing tests?

**Comment by hieuk09** [comment]
@joneslee85: I think this pull request will conflict with https://github.com/lotus/lotus/pull/166. I'm thinking about changing the code to resolve the conflict between them.

**Comment by joneslee85** [comment]
@hieuk09 it'd be best to wait till #166 is merged

**Comment by joneslee85** [comment]
@hieuk09 can you please rebase? cheers

**Comment by joneslee85** [comment]
@hieuk09 why closing this?

**Pull request closed without merging**
