### PR TITLE
Fix option at path when we mount lotus application apps inside container

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
# Problem
There is a problem when we mount applications inside lotus apps and we want generate urls or paths with routes helpers
```ruby
require 'lotus'

module Admin
  class Application < Lotus::Application
    configure do
      routes do
        get '/home', to: 'home#index', as: :home
      end
    end
  end
end

module CallCenter
  class Application < Lotus::Application
    configure do
      routes do
        get '/home', to: 'home#index', as: :home
      end
    end
  end
end

Lotus::Container.configure do
  mount Admin::Application, at: '/admin'
  mount CallCenter::Application, at: '/callcenter'
end

Lotus::Container.new

CallCenter::Routes.path(:home) # => '/home' WRONG
Admin::Routes.path(:home) # => '/home' WRONG
```
# Solution
Now with this PR fixes this problem

```ruby
require 'lotus'

module Admin
  class Application < Lotus::Application
    configure do
      routes do
        get '/home', to: 'home#index', as: :home
      end
    end
  end
end

module CallCenter
  class Application < Lotus::Application
    configure do
      routes do
        get '/home', to: 'home#index', as: :home
      end
    end
  end
end

Lotus::Container.configure do
  mount Admin::Application, at: '/admin'
  mount CallCenter::Application, at: '/callcenter'
end

Lotus::Container.new

CallCenter::Routes.path(:home) # => '/callcenter/home' GOOD
Admin::Routes.path(:home) # => '/admin/home' GOOD
```

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
@jodosha I don't know why fails here U_U

**Comment by jodosha** [comment]
@AlfonsoUceda This looks good. Once we get the other one merged, we can set the right gem version in `Gemfile` and we're done :clap:

**Comment by AlfonsoUceda** [comment]
https://travis-ci.org/lotus/lotus/jobs/66188639

```
➜  lotus git:(prefix_router) rake TESTOPTS="--seed=55799"                                            
Run options: --seed=55799

# Running:

......................................................WARN: tilt autoloading 'tilt/erb' in a non thread-safe way; explicit require 'tilt/erb' suggested.
............S.S....S...................................................................................................................................................................................................................S...............................................................................................................................................................................................................

Finished in 34.222214s, 14.4058 runs/s, 38.8344 assertions/s.

493 runs, 1329 assertions, 0 failures, 0 errors, 4 skips

You have skipped tests. Run with --verbose for details.
```

**Comment by AlfonsoUceda** [comment]
@jodosha can you try rerun?

**Comment by AlfonsoUceda** [comment]
weird :S
```
➜  router git:(force_ssl) chruby
 * ruby-2.0.0-p576
   ruby-2.1.5
➜  router git:(force_ssl) ruby -v
ruby 2.0.0p576 (2014-09-19) [x86_64-linux]
➜  router git:(force_ssl) rake test TESTOPTS="--seed=15737"
Run options: --seed=15737

# Running:

....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 3.933140s, 123.0569 runs/s, 333.8300 assertions/s.

484 runs, 1313 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by AlfonsoUceda** [comment]
@jodosha I removed keyword argument and replaced with hash argument

**Comment by jodosha** [comment]
@AlfonsoUceda Just merged. Thank you :+1:

**Pull request merged**
