### PR TITLE
Set correct definition for application and project words

### PR DESCRIPTION
**Pull request by davydovanton**
/cc @jodosha

### CODE REVIEW

**Comment by joneslee85** [comment]
I kinda like the wording project than application as it might be less confusing for users, but if we are to accept this PR, we need to update our API docs thoroughly too

**Comment by davydovanton** [comment]
@joneslee85 no problem. I can send PR with this changes to documentation too :blush:

**Comment by jodosha** [comment]
@joneslee85 The next version of the guides https://github.com/lotus/lotus.github.io/pull/114 is ready with the new terminology. I asked @davydovanton to open this PR.

**Comment by davydovanton** [comment]
thanks for merge, @jodosha! :+1:

**Pull request merged**
