### PR TITLE
Fix #453 issue

### LINKED ISSUE #453: Destroy command: removing app causes syntax error in config/environment.rb
Steps to reproduce

```shell
➜ lotus new bookshelf && cd bookshelf && bundle
➜ bundle exec lotus generate app admin
➜ bundle exec lotus destroy app admin
➜ cat config/environment.rb
require 'rubygems'
require 'bundler/setup'
require 'lotus/setup'
require_relative '../lib/bookshelf'bookshelf # SYNTAX ERROR
require_relative '../apps/web/application'

Lotus::Container.configure do
  mount Web::Application, at: '/'
end
```

---
Ref: #387
/cc @lucasallan

### PR DESCRIPTION
**Pull request by trexnix**
Hello. I did a tiny change and the issue has gone. Hope this helps :grimacing:

Closes #453

### CODE REVIEW

**Comment by jodosha** [comment]
@trexnix Hey, thank you! I tried it manually and it works great. Before to merge it, we need some tests to avoid future regressions.

Please have a look at this test and please enhance it: https://github.com/lotus/lotus/blob/master/test/commands/generate/app_test.rb#L87

Thank you!

**Comment by trexnix** [comment]
I updated tests for it. Please check them out @jodosha :smile:

**Comment by jodosha** [comment]
@trexnix This looks good, merging. Thank you very much! :+1:

**Comment by trexnix** [comment]
Great! You're welcome @jodosha :blush:

**Pull request merged**
