### PR TITLE
Adding a CONTRIBUTING.md to repository

### PR DESCRIPTION
**Pull request by jeremyf**
This is a pointer to a stubbed out contributing document. I don't
know if it is the correct point of reference, but it is something
I would like to see as a developer.

[skip ci]

### CODE REVIEW

**Comment by joneslee85** [comment]
@jeremyf Normally CONTRIBUTING outline the tech-side contribution guideline, for the sake of the convenience, I'd prefer we have the content ready within the file rather than redirecting users to another page

**Comment by jeremyf** [comment]
@joneslee85 Agreed. I have a [script for pushing out a contributing document to each repository](https://github.com/projecthydra/hydra/blob/master/script/push_contributing_document.rb). I believe it is project centric but would be easy to adapt; Should likely live in lotus-docs.

**Comment by jeremyf** [comment]
I'm more interested in opening up the conversation. I added a conversation issue on lotus-docs lotus/docs#18.

**Comment by jodosha** [comment]
I agree with @joneslee85 :smile:

**Comment by joneslee85** [comment]
@jeremyf to me we should maintain 2 versions, the long version which resides in docs repo would go into details the workflows whilst the CONTRIBUTING.md here should be related purely to style guideline , I kinda like the one of Spree https://github.com/spree/spree/blob/master/CONTRIBUTING.md

**Comment by joneslee85** [comment]
@jeremyf can you please kickstart this whenever you can? much thanks

**Comment by jeremyf** [comment]
I'm looking at Spree's CONTRIBUTING document and I like it as a baseline. One thing I'm concerned about is copying the CONTRIBUTING document verbatim; One I'd need to include a license, and two not all of it is applicable.

**Comment by joneslee85** [comment]
@jeremyf this looks a good starting point, let me know if you want me to merge it now

**Comment by jeremyf** [comment]
A few +1s would be great

On Thursday, March 12, 2015, Trung Lê <notifications@github.com> wrote:

> @jeremyf <https://github.com/jeremyf> this looks a good starting point,
> let me know if you want me to merge it now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lotus/lotus/pull/171#issuecomment-78730781>.
>


-- 

Jeremy Friesen
takeonrules.com

**Comment by thecatwasnot** [comment]
:+1:

**Comment by AlfonsoUceda** [comment]
:+1:

**Comment by jeremyf** [comment]
@AlfonsoUceda Once "ratified" and modified, I'd love to push that out. I have a script for pushing updates to CONTRIBUTING to all repositories of an organization https://github.com/projecthydra/hydra/blob/master/script/push_contributing_document.rb; It could be used and modified to automate that process (if there is a perceived volatility in the CONTRIBUTING document)

**Comment by jeremyf** [comment]
I'd love @jodosha to weigh in as well.

**Comment by AlfonsoUceda** [comment]
@jeremyf ok ;)

**Comment by jeremyf** [comment]
Or you know…go ahead and merge it!

**Comment by joneslee85** [comment]
@jeremyf till this day, I still have no clue about what `Lotus idiom` and the proper way to document the method. Maybe it's something that you could help with? I would love to adopt a strict code style if possible.

**Comment by jeremyf** [comment]
@joneslee85 If we are after a strict code style, then I would advocate that our builds should include Rubocop enforcement.

I've been doing it for [our application](https://github/ndlib/sipity) and am please with the results. Applying it to a project that is already started can be a bit of busy work; But there are ways to inch toward that.

This is our configuration https://github.com/ndlib/sipity/blob/master/.hound.yml (we were using Hound at one point, but abandoned it as Rubocop enforces things as part of `rake`).

**Comment by joneslee85** [comment]
@jeremyf I don't mind using Rubocop. What do you think @jodosha?

**Comment by jeremyf** [comment]
@joneslee85 based on a Gitter convesation, Rubocop is going to be angry; What I would like to see happen is that the contributing document be merged with "issues" being created to address any concerns.

A wise software developer once told me all we are doing is improving our approximations; So lets improve the documents by merging this pull request and (not &&) making an issue or two to address immediate shortcomings.

**Pull request merged**
