### PR TITLE
Added ruby-head in travis.yml

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by jodosha** [comment]
@ferdinandrosario Hello, and thank you for this PR. It's probably the case to list it under the allowed failures too. Can you please modify and rebase? Thank you.

**Comment by ferdinandrosario** [comment]
Sure @jodosha

**Comment by ferdinandrosario** [comment]
@jodosha I updated the travis file, could you please check?

**Comment by jodosha** [comment]
@ferdinandrosario Can you please squash commits? Thank you!

**Comment by ferdinandrosario** [comment]
@jodosha hope I did it correct.now for your revision :smile:

**Comment by jodosha** [comment]
@ferdinandrosario If you look at the [related build](https://travis-ci.org/lotus/lotus/builds/65047268) `ruby-head` isn't there. You should add it both to `rvm` and `allowed_failures` sections.

**Comment by ferdinandrosario** [comment]
done :+1:

**Comment by jodosha** [comment]
@ferdinandrosario Thank you! :+1:

**Comment by ferdinandrosario** [comment]
@jodosha Thanks for reviewing my novice mistake.. :+1:

**Pull request merged**
